version: '3.3'
services:
  api:
    build:
      context: ../api
      dockerfile: ./api.dev.Dockerfile
    container_name: Hawk-api
    restart: unless-stopped
    networks:
      - network
    volumes:
      - ../api:/usr/src/api
    expose:
      - 4000
    ports:
      - 4000:4000
    env_file: ../.env
    environment:
      WAIT_HOSTS: db:27018,redis:6379
      WAIT_HOSTS_TIMEOUT: 120
  db:
    image: mongo:latest
    container_name: DevOps_DB
    volumes:
      - ./data:/data/db
    ports:
      - 27018:27017
    networks:
      - network
  redis:
    image: redis:alpine
    container_name: Hawk-redis
    restart: unless-stopped
    networks:
      - network
  client:
    stdin_open: true
    build:
      context: ../client
      dockerfile: ./client.dev.Dockerfile
    container_name: DevOps_CLIENT
    restart: unless-stopped
    networks:
      - network
    volumes:
      - ../client:/usr/src/client
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_URI: client

networks:
  network:
    driver: bridge
